{ pkgs }:
# Org-wide pre-commit hook defaults for cachix/git-hooks.nix consumers.
#
# Consumers import the result into `pre-commit.settings.hooks`:
#
#   pre-commit.settings.hooks =
#     (inputs.nix-devenv.lib.mkPreCommitHooks { inherit pkgs; })
#     // {
#       # Per-repo additions or overrides go here (e.g. treefmt, which
#       # needs `package = config.treefmt.build.wrapper` from the local
#       # treefmt-nix config).
#     };
#
# Why a function, not a static attrset: hooks that shell out to a Nix
# package (markdownlint-cli2) need a `pkgs` reference resolved against
# the consumer's nixpkgs pin, not nix-devenv's.
#
# treefmt is intentionally NOT included: its `package` field must point
# at the consumer's locally-configured treefmt wrapper, which only the
# consumer can name.
{
  # Nix-source hygiene
  deadnix.enable = true;
  statix.enable = true;

  # Generic file hygiene
  check-yaml.enable = true;
  check-toml.enable = true;
  check-json.enable = true;
  check-merge-conflicts.enable = true;
  check-added-large-files = {
    enable = true;
    args = [ "--maxkb=500" ];
  };
  end-of-file-fixer.enable = true;
  # `--markdown-linebreak-ext=md` preserves Markdown's two-space line
  # breaks (where trailing whitespace is semantic, not garbage).
  trim-trailing-whitespace = {
    enable = true;
    args = [ "--markdown-linebreak-ext=md" ];
  };

  # Secret detection
  detect-private-keys.enable = true;

  # Markdown linting. markdownlint-cli2 has no native git-hooks.nix
  # wrapper, so configure it as a custom hook backed by the nixpkgs
  # package. CHANGELOG.md is auto-generated by release-please; its
  # commit-hash URLs trigger MD013 and per-release section headings
  # trigger MD024.
  markdownlint-cli2 = {
    enable = true;
    name = "markdownlint-cli2";
    entry = "${pkgs.markdownlint-cli2}/bin/markdownlint-cli2";
    files = "\\.md$";
    excludes = [ "^CHANGELOG\\.md$" ];
    language = "system";
    pass_filenames = true;
  };

  # GitHub Actions workflow security via zizmor. Persona/severity/
  # confidence chosen to match prior .pre-commit-config.yaml usage
  # across consuming repos.
  zizmor = {
    enable = true;
    files = "^\\.github/workflows/.*\\.ya?ml$";
    args = [
      "--persona=regular"
      "--min-severity=medium"
      "--min-confidence=medium"
    ];
  };
}
